### ISSUE TITLE
Unable to serve static files via HTTP/2

### ISSUE THREAD

**Issue by brano543** [cutelyst/cutelyst#187] opened 2019-02-26 14:18 UTC
Hi,

it seems that this line https://github.com/cutelyst/cutelyst/blob/master/Cutelyst/Plugins/StaticSimple/staticsimple.cpp#L77
returns "/" at start when HTTP/2 over SSL is used (wsgi->setHttpsH2(true)) resulting in files not being able to be found.

Way to replicate
```
int main(int argc, char *argv[])
{
  CWSGI::WSGI *wsgi = new CWSGI::WSGI();
  Cutelyst::Application *myapp = new Hello();
  QCoreApplication app(argc, argv);
  wsgi->setProcesses("1");
  wsgi->setThreads("4");
  wsgi->setHttpsSocket({{QStringLiteral("0.0.0.0:443,/etc/ssl/certs/certificate.crt,/etc/ssl/private/server.key")}});
  wsgi->setHttpsH2(true);
  wsgi->setBufferSize(16393);
  wsgi->setSoKeepalive(true);
  wsgi->setReusePort(true);
  wsgi->setMaster(true);
  wsgi->exec(myapp);
}
```
```
bool Hello::init()
{
    //initialize controllers
    new Root(this);

    //initialize file serving plugin
    auto staticSimple = new StaticSimple(this);
    staticSimple->setDirs({"public"});
    staticSimple->setIncludePaths({QDir::currentPath()});

    //initialize templates plugin
    auto grantleeView = new GrantleeView(this);
    grantleeView->setCache(true);
    grantleeView->setIncludePaths({pathTo("views")});

    return true;
}
```

Even when I fix the line to 
`const QString path = c->req()->path().mid(1);`
for this scenario and files can actually be found, I am getting net::ERR_SPDY_FRAME_SIZE_ERROR.

**Comment by brano543** [comment] 2019-02-26 14:39
This code and setHttpsH2(true) results in above mentioned error.
```
 QFile *file = new QFile("/opt/pandora_api/public/img/logo.png");
    if (file->open(QFile::ReadOnly))
    {
        c->response()->setBody(file);
        c->response()->headers().setContentLength(file->size());
    }
```

**Comment by dantti** [comment] 2019-02-28 11:21
Does it work on H2C?

**Comment by dantti** [comment] 2019-02-28 21:02
I think I could reproduce the issue, but as a side note, avoid using the static simple plugin, static-map option of WSGI is a better option.

**Comment by dantti** [comment] 2019-02-28 21:13
Oh, and you also don't need to manually set the content length header, it will use the QIODevice::size()

**Comment by dantti** [comment] 2019-02-28 21:17
I can't reproduce your issue with 
net::ERR_SPDY_FRAME_SIZE_ERROR
works for me when manually setting a file.

Please check if this commit fix your issue

**Comment by brano543** [comment] 2019-03-05 14:31
Hello, the latest commit unfortunately made the issue even worse. Previous commit 9b3ce6f  it at least showed index.html, but latest commit dd5ce05 I can't even reach the index. If I comment out setHttpsH2 it will work using TLS and HTTP/1.1. I will test if it will work using H2C behind haproxy.

```
wsgi->setProcesses("1");
  wsgi->setThreads("4");
  wsgi->setHttpsSocket({{QStringLiteral("0.0.0.0:443,/etc/ssl/certs/certificate.crt,/etc/ssl/private/server.key")}});
  wsgi->setHttpsH2(true);
  wsgi->setBufferSize(16393);
  wsgi->setSoKeepalive(true);
  wsgi->setReusePort(true);
  wsgi->setMaster(true);
  wsgi->setStaticMap({"/public=" + QDir::currentPath() + "/public"});
  wsgi->exec(myapp);
```

**Comment by brano543** [comment] 2019-03-05 17:57
H2C is not working. It only works with plain http/1.1 (HttpSocket and by removing h2 directive from haproxy config). Steps to reproduce. 
```
wsgi->setProcesses("1");
  wsgi->setThreads("4");
  wsgi->setHttp2Socket({{QStringLiteral("0.0.0.0:8000")}});
  wsgi->setBufferSize(16393);
  wsgi->setSoKeepalive(true);
  wsgi->setReusePort(true);
  wsgi->setMaster(true);
  wsgi->setStaticMap({"/public=" + QDir::currentPath() + "/public"});
  wsgi->exec(myapp);
```
Haproxy config
```
global
    # *** Process management ***
    tune.ssl.default-dh-param 2048
    nbproc 1                        # 1 process
    nbthread 8                      # 8 threads
    cpu-map auto:1/1-8  0-7         # bind all threads of the first process on the first 8 cores (0-7)
    user pandora
    group pandora
    
    # *** Performance tuning ***
    maxconn 2000
    maxconnrate 2000

defaults
    timeout connect 5000
    timeout client 10000
    timeout server 10000
    
frontend pandora_front
    mode tcp 
    bind 0.0.0.0:443 ssl crt /etc/ssl/certs/certificate_key.pem alpn h2,http/1.1
    default_backend pandora_server

backend pandora_server
    mode tcp 
    server pandora_backend_server 0.0.0.0:8000
```

**Comment by dantti** [comment] 2019-03-06 00:45
What you want to do is not possible according to:
https://stackoverflow.com/a/48476032/5673090
Nginx also cannot talk to H2 backends

**Comment by brano543** [comment] 2019-03-06 14:04
Thank you for your reply. You are right it is supported only from Haproxy 1.9. However there is still problem in Cutelyst not handling H2c properly. 
```
curl --version
curl 7.64.0 (x86_64-redhat-linux-gnu) libcurl/7.64.0 NSS/3.36 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.8.0 nghttp2/1.31.1
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy PSL Metalink 
```
Curl gives this error
```
curl --http2-prior-knowledge http://localhost:8000
curl: (16) Error in the HTTP2 framing layer
```
I also tried to run h2spec(https://github.com/summerwind/h2spec) to find possible errors.  I think what we should consider as error is in section 6.5.3 and consequently 6.9.1, 6.9.2, 6.10.  Problem is in headers frame.
```
Failures: 

Hypertext Transfer Protocol Version 2 (HTTP/2)
  4. HTTP Frames
    4.3. Header Compression and Decompression
      × 1: Sends invalid header block fragment
        -> The endpoint MUST terminate the connection with a connection error of type COMPRESSION_ERROR.
           Expected: GOAWAY Frame (Error Code: COMPRESSION_ERROR)
                     Connection closed
             Actual: Timeout

  5. Streams and Multiplexing
    5.1. Stream States
      × 1: idle: Sends a DATA frame
        -> The endpoint MUST treat this as a connection error of type PROTOCOL_ERROR.
           Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                     Connection closed
             Actual: Timeout
      × 2: idle: Sends a RST_STREAM frame
        -> The endpoint MUST treat this as a connection error of type PROTOCOL_ERROR.
           Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                     Connection closed
             Actual: Timeout
      × 3: idle: Sends a WINDOW_UPDATE frame
        -> The endpoint MUST treat this as a connection error of type PROTOCOL_ERROR.
           Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                     Connection closed
             Actual: Timeout
      × 6: half closed (remote): Sends a HEADERS frame
        -> The endpoint MUST respond with a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout
      × 9: closed: Sends a HEADERS frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout
      × 11: closed: Sends a DATA frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: Stream closed
             Actual: GOAWAY Frame (length:8, flags:0x00, stream_id:0)
      × 12: closed: Sends a HEADERS frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: Stream closed
             Actual: GOAWAY Frame (length:8, flags:0x00, stream_id:0)
      × 13: closed: Sends a CONTINUATION frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: Stream closed
             Actual: GOAWAY Frame (length:8, flags:0x00, stream_id:0)

    5.4. Error Handling
      5.4.1. Connection Error Handling
        × 1: Sends an invalid PING frame for connection close
          -> The endpoint MUST close the TCP connection
             Expected: Connection closed
               Actual: GOAWAY Frame (length:8, flags:0x00, stream_id:0)

  6. Frame Definitions
    6.4. RST_STREAM
      × 2: Sends a RST_STREAM frame on a idle stream
        -> The endpoint MUST respond with a connection error of type PROTOCOL_ERROR.
           Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                     Connection closed
             Actual: Timeout

    6.5. SETTINGS
      6.5.3. Settings Synchronization
        × 1: Sends multiple values of SETTINGS_INITIAL_WINDOW_SIZE
        Error: Unable to get server data length

    6.9. WINDOW_UPDATE
      × 3: Sends a WINDOW_UPDATE frame with a length other than 4 octets
        -> The endpoint MUST treat this as a connection error of type FRAME_SIZE_ERROR.
           Expected: GOAWAY Frame (Error Code: FRAME_SIZE_ERROR)
                     Connection closed
             Actual: Timeout

      6.9.1. The Flow-Control Window
        × 1: Sends SETTINGS frame to set the initial window size to 1 and sends HEADERS frame
        Error: Unable to get server data length

      6.9.2. Initial Flow-Control Window Size
        × 1: Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame
        Error: Unable to get server data length
        × 2: Sends a SETTINGS frame for window size to be negative
        Error: Unable to get server data length

    6.10. CONTINUATION
      × 1: Sends multiple CONTINUATION frames preceded by a HEADERS frame
        -> The endpoint must accept the frame.
           Expected: HEADERS Frame (stream_id:1)
             Actual: GOAWAY Frame (length:8, flags:0x00, stream_id:0)

Finished in 34.1695 seconds
94 tests, 76 passed, 1 skipped, 17 failed
```

I tried it with Haproxy 1.9 and it doesn't work with Cutelyst while with H2O it works. Steps to reproduce:
Haproxy.config
```
 global
    tune.ssl.default-dh-param 2048
    nbproc 1                        # 1 process
    nbthread 8                      # 8 threads
    cpu-map auto:1/1-8  0-7         # bind all threads of the first process on the first 8 cores (0-7)
    user pandora
    group pandora
    
    # *** Performance tuning ***
    maxconn 2000
    maxconnrate 2000

defaults
    timeout connect 5000
    timeout client 10000
    timeout server 10000
    
frontend pandora_front
    mode http
    option http-use-htx
    bind 0.0.0.0:443 ssl crt /etc/ssl/certs/certificate_key.pem alpn h2,http/1.1
    default_backend pandora_server

backend pandora_server
    mode http
    option http-use-htx
    server pandora_backend_server 0.0.0.0:8000 proto h2
```
Cutelyst code
```
  wsgi->setProcesses("1");
  wsgi->setThreads("4");
  wsgi->setHttp2Socket({{QStringLiteral("0.0.0.0:8000")}});
  wsgi->setBufferSize(16393);
  wsgi->setSoKeepalive(true);
  wsgi->setReusePort(true);
  wsgi->setMaster(true);
  wsgi->setStaticMap({"/public=" + QDir::currentPath() + "/public"});
  wsgi->exec(myapp);
```
I tested this with H2o standalone server and it works, so there is bug in H2c support somewhere. 
h2o config
```
# global options
user: pandora
access-log: /opt/pandora_api/build/bin/access.log
error-log: /opt/pandora_api/build/bin/error.log
pid-file: /opt/pandora_api/build/bin/pid.txt

hosts:
  "m3106026.go.johnsoncontrols.com:8000":
    listen:
      host: 0.0.0.0
      port: 8000
    paths:
      "/public":
        file.dir: /opt/pandora_api/public

```

**Comment by dantti** [comment] 2019-03-06 17:10
I've found the issue that only happens due my previous fix.
Cutelyst used to pass all those tests, I might need to review them.

**Comment by dantti** [comment] 2019-03-13 00:18
can I close the issue?

**Comment by brano543** [comment] 2019-03-13 13:08
Issue still persists. Now some files succeed, but some just don't and they are even under same folder structure:
/public/javascripts/select2_4.0.5.min.js fails with net::ERR_SPDY_PROTOCOL_ERROR
/public/javascripts/ succeeds

**Comment by dantti** [comment] 2019-03-13 13:14
Do you mind creating a simple git repo with a small example app and files that fail?

That warning might happen because the client closes the connection prematurely, or there's is some bug that I could not find yet.

**Comment by dantti** [comment] 2019-06-21 00:17
Some fixes for H2 were merged into master, could you try testing again?

**Comment by brano543** [comment] 2019-07-02 21:17
Hello Daniel,

I am unfortunately really busy at the moment with one project since we had
to switch from C++ to Javascript. I will test it when I find time. Thank
you for all your dedication to this project.

pi 21. 6. 2019 o 2:17 Daniel Nicoletti <notifications@github.com>
napísal(a):

**Comment by dantti** [comment] 2019-12-29 15:39
Closing as it works for me.

**Closed by dantti** 2019-12-29 15:39 UTC
